name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Adjust branch name as per your repo structure

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # Adjust Node version according to your project

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # Adjust the build command based on your project

      - name: Deploy to Vercel
        run: |
          npm i -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
